version: '3.4'

services:
  mamikost:
    image: mamikost
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8888
    depends_on:
      - postgresDB
    networks:
      - local_net

  postgresDB:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mamikost_dbx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_net

volumes:
  postgres_data:

networks:
  local_net:
    driver: bridge
