###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

#host.docker.internal
[database]

connection_string = "postgres://postgres:admin@postgresDB:5432/mamikost_dbx?sslmode=disable"
max_idle_connections = 5
max_open_connections = 10
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[migration]

migration_path="db/migrations"
db_url ="postgres://postgres:admin@postgresDB:5432/mamikost_dbx?sslmode=disable"
db_username = "postgres"
db_password = "admin"
db_dbname = "mamikost_dbx"
db_port = "5432"
db_hostname = "postgresDB"
db_recreate = "true"

[http]
host = "localhost"
server_address = ":8888"
###############################################################################

[jwt]

api_secret="mysecret"
token_hour_lifespan="24h"
###############################################################################
