// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddOrderDetail(ctx context.Context, arg AddOrderDetailParams) (*OrderRentPropertiesDetail, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCategory(ctx context.Context, cateName string) (int32, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*OrderRentProperty, error)
	CreateRentProperty(ctx context.Context, arg CreateRentPropertyParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteAllImagesForProperty(ctx context.Context, frimRepoID *int32) error
	DeleteCart(ctx context.Context, cartID int32) error
	DeleteCategory(ctx context.Context, cateID int32) error
	DeleteImageByID(ctx context.Context, frimID int32) error
	DeleteOrder(ctx context.Context, orpoID int32) error
	DeleteRentProperty(ctx context.Context, repoID int32) error
	DeleteToken(ctx context.Context, userToken *string) error
	FindAllOrders(ctx context.Context) ([]*OrderRentProperty, error)
	FindCartByUserandRentProperty(ctx context.Context, arg FindCartByUserandRentPropertyParams) (*FindCartByUserandRentPropertyRow, error)
	FindOrderByID(ctx context.Context, orpoID int32) (*OrderRentProperty, error)
	FindUserByPhone(ctx context.Context, userPhone string) (*FindUserByPhoneRow, error)
	FindUserByUserPassword(ctx context.Context, arg FindUserByUserPasswordParams) (*FindUserByUserPasswordRow, error)
	FindUserByUsername(ctx context.Context, userName string) (*FindUserByUsernameRow, error)
	GetAllCategories(ctx context.Context) ([]*Category, error)
	GetAllImages(ctx context.Context) ([]*RentPropertiesImage, error)
	GetAllItemsForOrder(ctx context.Context, orpdOrpoID *int32) ([]*GetAllItemsForOrderRow, error)
	GetAllRentProperties(ctx context.Context) ([]*RentProperty, error)
	GetCartByUserID(ctx context.Context, cartUserID *int32) ([]*GetCartByUserIDRow, error)
	GetCategoryByID(ctx context.Context, cateID int32) (*Category, error)
	GetImageByID(ctx context.Context, frimID int32) (*RentPropertiesImage, error)
	GetRentPropertyByID(ctx context.Context, repoID int32) (*RentProperty, error)
	RemoveItemFromOrder(ctx context.Context, orpdID int32) error
	UpdateCart(ctx context.Context, arg UpdateCartParams) (*Cart, error)
	UpdateCartQty(ctx context.Context, arg UpdateCartQtyParams) (*Cart, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*OrderRentProperty, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	UpdateOrderPatrxNo(ctx context.Context, arg UpdateOrderPatrxNoParams) (*OrderRentProperty, error)
	UpdateOrderSubtotal(ctx context.Context, orpoID int32) (*OrderRentProperty, error)
	UpdateOrderTotalAndTax(ctx context.Context, orpoID int32) (*OrderRentProperty, error)
	UpdateRentProperty(ctx context.Context, arg UpdateRentPropertyParams) error
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (*User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (*User, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (*User, error)
	UploadImage(ctx context.Context, arg UploadImageParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
